### ISSUE TITLE
Display a pill on the camera screen of the last guest that was checked in

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-android-doorperson#17]
Related to #16 
![image](https://user-images.githubusercontent.com/41575888/56639486-14ee2600-6671-11e9-8cfe-80a86d83abb8.png)

**Comment by Krakaw** [comment]
If the user details include a thumbnail image url you can display the user profile image, the user's name, the ticket type and if the checkin was successful or not

**Comment by githubsrki** [comment]
The last check-in pill is shown after every check in
